AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Embedding service

Parameters:
  ServiceName:
    Type: String
    Description: Name of the service
  ImageRepoUri:
    Type: String
    Description: URI of service image
  Stage:
    Type: String
    Description: API Stage prefix
  Uuid:
    Type: String
    Description: ChangeSet UUID

Resources:
  
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: !Sub /lambda/execution/${ServiceName}-embedding/
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-embedding
      Role: !GetAtt Role.Arn
      PackageType: Image
      MemorySize: 4096
      Timeout: 90
      Code:
        ImageUri: !Sub "${ImageRepoUri}:${Uuid}"

  KeepWarmInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Function.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt KeepWarm.Arn

  KeepWarm:
    Type: AWS::Events::Rule
    Properties:
      Description: Keep warm for lambda function
      Name: !Sub ${ServiceName}-embedding-keepwarm
      ScheduleExpression: rate(4 minutes)
      Targets: 
        - Arn: !GetAtt Function.Arn
          Id: SentenceEmbeddingsKeepWarm
          Input: '{"body":"{\"sentences\":[\"This event spits hot fire to keep the function warm!\"]}"}'

  ApiGateWayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${Function.Arn}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*'

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${ServiceName}-embedding-gateway
      Description: Sentence Embeddings API

  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      RestApiId: !Ref RestApi
      PathPart: encode

  ProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      ApiKeyRequired: true
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        IntegrationResponses:
          - StatusCode: 200
          - StatusCode: 400
          - StatusCode: 500
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt Function.Arn
      ResourceId: !Ref ProxyResource
      RestApiId: !Ref RestApi

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProxyMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: !Ref Stage