AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Embedding service

Parameters:
  ServiceName:
    Type: String
    Description: Name of the service
  Uuid:
    Type: String
    Description: ChangeSet UUID

Resources:
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      Tags:
        - Key: Uuid
          Value: !Ref Uuid
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub ${ServiceName}-embedding-rt
      RepositoryPolicyText: !Sub |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "AllowCrossAccountPush",
                    "Effect": "Allow",
                    "Principal": {
                        "AWS": "arn:aws:iam::${AWS::AccountId}:root"
                    },
                    "Action": [
                        "ecr:BatchCheckLayerAvailability",
                        "ecr:CompleteLayerUpload",
                        "ecr:InitiateLayerUpload",
                        "ecr:PutImage",
                        "ecr:UploadLayerPart"
                    ]
                },
                {
                    "Sid": "LambdaECRImageRetrievalPolicy",
                    "Effect": "Allow",
                    "Principal": {
                      "Service": "lambda.amazonaws.com"
                    },
                    "Action": [
                      "ecr:BatchGetImage",
                      "ecr:GetDownloadUrlForLayer"
                    ]
                }
            ]
        }